### PR TITLE
Feature/newlogo

### PR DESCRIPTION
**Pull request by clawfire**
Elle est ici ma PR pour le logo @metal3d  ;)

### CODE REVIEW

**Comment by metal3d** [comment]
Some lacks:

- We need logo-dark (inverted) for some components
- Font is not vectorized, so doesn't display as it should

**Comment by clawfire** [comment]
Regarding the dark logo ... I find the regular one working quite good on both case. Could you provide some screenshot where it's ugly ?  Cheers :)

**Comment by metal3d** [comment]
Didn't checked, but I trust you.

Anyway, the rebase is not ok. You merged master in your branch - can you please rebase on "devel" removing commits that are not in your specific branch ?

**Comment by metal3d** [comment]
One more note: PR on *devel* not on master

**Comment by metal3d** [comment]
Because the branch is not cleaned and logo is not entirely changed in templates, I've taken your branch, rebased and I'm currently making needed changes.
See #42

**Pull request closed without merging**
